@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniqueLessonList
AddressBook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueLessonList
UniqueTagList -[hidden]down- UniqueLessonList

UniqueTagList -right-> "*" Tag
UniqueLessonList -right-> Lesson

Lesson -up-> "*" Tag

Lesson *--> "1" Name
Lesson *--> "1" Phone
Lesson *--> "1" Email
Lesson *--> "1" Address
Lesson *--> "1" Day
Lesson *--> "1" Time : startTime
Lesson *--> "1" Time : endTime
Lesson *--> "1" Rate
@enduml
